package main

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"log"
	"os"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/redis/go-redis/v9"
	redisrepo "github.com/tcandt/cloudphone-farm/backend/internal/repository/redis"
	"github.com/tcandt/cloudphone-farm/backend/pkg/crypto"
)

const (
	OrgID    = "org_e2e_phase2"
	UserID   = "user_e2e_phase2"
	MemberID = "membership_e2e_phase2"
)

func generateRawToken() string {
	b := make([]byte, 32)
	rand.Read(b)
	return hex.EncodeToString(b)
}

func main() {
	if len(os.Args) < 2 {
		log.Fatalf("Usage: e2e-session-seed [seed|cleanup] [tokenHash(for cleanup)]")
	}
	action := os.Args[1]

	ctx := context.Background()
	
	pgUrl := os.Getenv("POSTGRES_URL")
	if pgUrl == "" {
		pgUrl = "postgresql://postgres:postgres@localhost:5432/postgres?sslmode=disable"
	}
	pool, err := pgxpool.New(ctx, pgUrl)
	if err != nil {
		log.Fatalf("Failed to connect to Postgres: %v", err)
	}
	defer pool.Close()

	redisUrl := os.Getenv("REDIS_URL")
	if redisUrl == "" {
		redisUrl = "localhost:6379"
	}
	rdb := redis.NewClient(&redis.Options{Addr: redisUrl})
	defer rdb.Close()
	sessionRepo := redisrepo.NewSessionRepository(rdb)

	if action == "seed" {
		// UPSERT Org
		_, err = pool.Exec(ctx, `
			INSERT INTO organizations (organization_id, name, slug, created_at, updated_at)
			VALUES ($1, 'E2E Phase 2 Org', 'e2e-phase2-org', NOW(), NOW())
			ON CONFLICT (organization_id) DO NOTHING
		`, OrgID)
		if err != nil {
			log.Fatalf("Failed to upsert org: %v", err)
		}

		// UPSERT User
		_, err = pool.Exec(ctx, `
			INSERT INTO users (user_id, email, password_hash, display_name, created_at, updated_at)
			VALUES ($1, 'admin_e2e@phonecontrol.io', 'hash', 'E2E Admin', NOW(), NOW())
			ON CONFLICT (user_id) DO NOTHING
		`, UserID)
		if err != nil {
			log.Fatalf("Failed to upsert user: %v", err)
		}

		// UPSERT Membership
		_, err = pool.Exec(ctx, `
			INSERT INTO organization_memberships (membership_id, organization_id, user_id, status, joined_at)
			VALUES ($1, $2, $3, 'active', NOW())
			ON CONFLICT (membership_id) DO NOTHING
		`, MemberID, OrgID, UserID)
		if err != nil {
			log.Fatalf("Failed to upsert membership: %v", err)
		}

		rawToken := generateRawToken()
		tokenHash := crypto.HashToken(rawToken)

		data := &redisrepo.SessionData{
			SessionID:      "sess_e2e_phase2",
			UserID:         UserID,
			Email:          "admin_e2e@phonecontrol.io",
			DisplayName:    "E2E Admin",
			OrganizationID: OrgID,
			MembershipID:   MemberID,
			Roles:          []string{"owner"},
			Permissions: map[string]struct{}{
				"agent.enroll": {},
				"agent.read":   {},
				"agent.revoke": {},
			},
		}

		err = sessionRepo.CreateSession(ctx, tokenHash, data, 24*time.Hour)
		if err != nil {
			log.Fatalf("Failed to create session: %v", err)
		}

		// Output raw token in JSON
		out, _ := json.Marshal(map[string]string{
			"raw_token": rawToken,
			"token_hash": tokenHash,
		})
		fmt.Println(string(out))

	} else if action == "cleanup" {
		if len(os.Args) < 3 {
			log.Fatalf("cleanup requires tokenHash argument")
		}
		tokenHash := os.Args[2]

		// Cleanup Session
		rdb.Del(ctx, "pcp:session:v1:"+tokenHash)

		// Cleanup keys/bindings generated by this user/org (for E2E runs)
		// Best-effort cleanup so later runs are clean
		pool.Exec(ctx, "DELETE FROM agent_enrollment_keys WHERE organization_id = $1", OrgID)

		fmt.Println("cleanup ok")
	}
}
