// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package http

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
	CookieAuthScopes = "cookieAuth.Scopes"
)

// Defines values for DeviceCommandStatus.
const (
	Ack       DeviceCommandStatus = "ack"
	Executing DeviceCommandStatus = "executing"
	Failed    DeviceCommandStatus = "failed"
	Pending   DeviceCommandStatus = "pending"
	Succeeded DeviceCommandStatus = "succeeded"
)

// Defines values for DeviceEntityStatus.
const (
	DeviceEntityStatusDegraded     DeviceEntityStatus = "degraded"
	DeviceEntityStatusMaintenance  DeviceEntityStatus = "maintenance"
	DeviceEntityStatusOffline      DeviceEntityStatus = "offline"
	DeviceEntityStatusOnline       DeviceEntityStatus = "online"
	DeviceEntityStatusProvisioning DeviceEntityStatus = "provisioning"
	DeviceEntityStatusRetired      DeviceEntityStatus = "retired"
	DeviceEntityStatusRevoked      DeviceEntityStatus = "revoked"
)

// Defines values for DispatchCommandRequestType.
const (
	ApkInstall        DispatchCommandRequestType = "apk.install"
	DeviceLock        DispatchCommandRequestType = "device.lock"
	DeviceReboot      DispatchCommandRequestType = "device.reboot"
	GestureSwipe      DispatchCommandRequestType = "gesture.swipe"
	GestureTouch      DispatchCommandRequestType = "gesture.touch"
	GlobalBack        DispatchCommandRequestType = "global.back"
	GlobalHome        DispatchCommandRequestType = "global.home"
	GlobalRecents     DispatchCommandRequestType = "global.recents"
	InputText         DispatchCommandRequestType = "input.text"
	NetworkProxyApply DispatchCommandRequestType = "network.proxy.apply"
	ScreenCapture     DispatchCommandRequestType = "screen.capture"
	ScreenRotate      DispatchCommandRequestType = "screen.rotate"
)

// Defines values for EnrollmentTokenStatus.
const (
	EnrollmentTokenStatusActive   EnrollmentTokenStatus = "active"
	EnrollmentTokenStatusConsumed EnrollmentTokenStatus = "consumed"
	EnrollmentTokenStatusExpired  EnrollmentTokenStatus = "expired"
	EnrollmentTokenStatusRevoked  EnrollmentTokenStatus = "revoked"
)

// AgentEnrollRequest defines model for AgentEnrollRequest.
type AgentEnrollRequest struct {
	ChallengeId      string `json:"challenge_id"`
	ClientInstanceId string `json:"client_instance_id"`
	DeviceInfo       struct {
		AgentVersion    string `json:"agent_version"`
		AndroidVersion  string `json:"android_version"`
		Manufacturer    string `json:"manufacturer"`
		Model           string `json:"model"`
		ProtocolVersion string `json:"protocol_version"`
		SdkInt          int    `json:"sdk_int"`
		SerialNumber    string `json:"serial_number"`
	} `json:"device_info"`
	EnrollmentToken string `json:"enrollment_token"`
	PublicKey       string `json:"public_key"`
	Signature       string `json:"signature"`
}

// AgentEnrollResponse defines model for AgentEnrollResponse.
type AgentEnrollResponse struct {
	AgentId           string `json:"agent_id"`
	CredentialVersion int    `json:"credential_version"`
	DeviceId          string `json:"device_id"`
	OrganizationId    string `json:"organization_id"`
	Status            string `json:"status"`
}

// AgentKey defines model for AgentKey.
type AgentKey struct {
	ActiveBindings int        `json:"active_bindings"`
	CreatedAt      time.Time  `json:"created_at"`
	CreatedBy      string     `json:"created_by"`
	ExpiresAt      *time.Time `json:"expires_at"`
	KeyId          string     `json:"key_id"`
	LastUsedAt     *time.Time `json:"last_used_at"`
	MaxBindings    *int       `json:"max_bindings"`
	Name           string     `json:"name"`
	OrganizationId string     `json:"organization_id"`
	RevokedAt      *time.Time `json:"revoked_at"`
	TokenPrefix    string     `json:"token_prefix"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

// AgentKeyBinding defines model for AgentKeyBinding.
type AgentKeyBinding struct {
	AgentId              string     `json:"agent_id"`
	BindingId            string     `json:"binding_id"`
	BoundAt              time.Time  `json:"bound_at"`
	DeviceId             string     `json:"device_id"`
	PublicKeyFingerprint string     `json:"public_key_fingerprint"`
	ReleaseReason        *string    `json:"release_reason"`
	ReleasedAt           *time.Time `json:"released_at"`
}

// AgentKeyCreatedResponse defines model for AgentKeyCreatedResponse.
type AgentKeyCreatedResponse struct {
	Key       AgentKey `json:"key"`
	RawSecret string   `json:"raw_secret"`
}

// AuditLogItem defines model for AuditLogItem.
type AuditLogItem struct {
	ActionCode     string  `json:"action_code"`
	ActorEmail     *string `json:"actor_email,omitempty"`
	ActorId        string  `json:"actor_id"`
	AuditId        string  `json:"audit_id"`
	CreatedAt      string  `json:"created_at"`
	Details        *string `json:"details,omitempty"`
	IpAddress      *string `json:"ip_address,omitempty"`
	OrganizationId string  `json:"organization_id"`
	ResourceId     string  `json:"resource_id"`
	ResourceType   string  `json:"resource_type"`
}

// ControlLease defines model for ControlLease.
type ControlLease struct {
	AcquiredAt      string  `json:"acquired_at"`
	ControlLeaseId  string  `json:"control_lease_id"`
	DeviceId        string  `json:"device_id"`
	ExpiresAt       string  `json:"expires_at"`
	FencingToken    int64   `json:"fencing_token"`
	OrganizationId  string  `json:"organization_id"`
	TtlSeconds      int     `json:"ttl_seconds"`
	UserDisplayName *string `json:"user_display_name,omitempty"`
	UserId          string  `json:"user_id"`
}

// DeviceCommand defines model for DeviceCommand.
type DeviceCommand struct {
	ActorId        string              `json:"actor_id"`
	ActorName      string              `json:"actor_name"`
	CommandId      string              `json:"command_id"`
	CommandType    string              `json:"command_type"`
	CreatedAt      string              `json:"created_at"`
	DeviceId       string              `json:"device_id"`
	OrganizationId string              `json:"organization_id"`
	Status         DeviceCommandStatus `json:"status"`
}

// DeviceCommandStatus defines model for DeviceCommand.Status.
type DeviceCommandStatus string

// DeviceEntity defines model for DeviceEntity.
type DeviceEntity struct {
	AndroidVersion string                  `json:"android_version"`
	Capabilities   *map[string]interface{} `json:"capabilities,omitempty"`
	DeviceId       string                  `json:"device_id"`
	DisplayName    string                  `json:"display_name"`
	Model          string                  `json:"model"`
	OrganizationId string                  `json:"organization_id"`
	SerialNumber   string                  `json:"serial_number"`
	Status         DeviceEntityStatus      `json:"status"`
	Telemetry      *map[string]interface{} `json:"telemetry,omitempty"`
}

// DeviceEntityStatus defines model for DeviceEntity.Status.
type DeviceEntityStatus string

// DispatchCommandRequest defines model for DispatchCommandRequest.
type DispatchCommandRequest struct {
	ControlLeaseId string                     `json:"controlLeaseId"`
	DeviceId       string                     `json:"deviceId"`
	ExpiresAt      *string                    `json:"expiresAt,omitempty"`
	IdempotencyKey string                     `json:"idempotencyKey"`
	IssuedAt       *string                    `json:"issuedAt,omitempty"`
	Payload        map[string]interface{}     `json:"payload"`
	Type           DispatchCommandRequestType `json:"type"`
}

// DispatchCommandRequestType defines model for DispatchCommandRequest.Type.
type DispatchCommandRequestType string

// EnrollmentToken defines model for EnrollmentToken.
type EnrollmentToken struct {
	BoundGroupId   *string               `json:"bound_group_id,omitempty"`
	CreatedAt      string                `json:"created_at"`
	CreatedBy      string                `json:"created_by"`
	ExpiresAt      string                `json:"expires_at"`
	OrganizationId string                `json:"organization_id"`
	Status         EnrollmentTokenStatus `json:"status"`
	TokenId        string                `json:"token_id"`
}

// EnrollmentTokenStatus defines model for EnrollmentToken.Status.
type EnrollmentTokenStatus string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code      string                  `json:"code"`
	Details   *map[string]interface{} `json:"details,omitempty"`
	Message   string                  `json:"message"`
	Timestamp time.Time               `json:"timestamp"`
}

// UserSession defines model for UserSession.
type UserSession struct {
	DisplayName      string    `json:"display_name"`
	Email            string    `json:"email"`
	OrganizationId   string    `json:"organization_id"`
	OrganizationName *string   `json:"organization_name,omitempty"`
	Permissions      []string  `json:"permissions"`
	Role             string    `json:"role"`
	Roles            *[]string `json:"roles,omitempty"`
	UserId           string    `json:"user_id"`
}

// BadRequestError defines model for BadRequestError.
type BadRequestError = ErrorResponse

// ConflictError defines model for ConflictError.
type ConflictError = ErrorResponse

// ForbiddenError defines model for ForbiddenError.
type ForbiddenError = ErrorResponse

// NotFoundError defines model for NotFoundError.
type NotFoundError = ErrorResponse

// UnauthorizedError defines model for UnauthorizedError.
type UnauthorizedError = ErrorResponse

// PostAgentKeysJSONBody defines parameters for PostAgentKeys.
type PostAgentKeysJSONBody struct {
	ExpiresAt   *time.Time `json:"expires_at"`
	MaxBindings *int       `json:"max_bindings"`
	Name        string     `json:"name"`
}

// PatchAgentKeysKeyIdJSONBody defines parameters for PatchAgentKeysKeyId.
type PatchAgentKeysKeyIdJSONBody struct {
	ExpiresAt   *time.Time `json:"expires_at"`
	MaxBindings *int       `json:"max_bindings"`
	Name        *string    `json:"name,omitempty"`
}

// PostAgentsEnrollChallengeJSONBody defines parameters for PostAgentsEnrollChallenge.
type PostAgentsEnrollChallengeJSONBody struct {
	ClientInstanceId string `json:"client_instance_id"`
	EnrollmentToken  string `json:"enrollment_token"`
	PublicKey        string `json:"public_key"`
}

// GetAuditLogsParams defines parameters for GetAuditLogs.
type GetAuditLogsParams struct {
	Page *int `form:"page,omitempty" json:"page,omitempty"`
}

// PostAuthLoginJSONBody defines parameters for PostAuthLogin.
type PostAuthLoginJSONBody struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// GetDevicesParams defines parameters for GetDevices.
type GetDevicesParams struct {
	Status  *string `form:"status,omitempty" json:"status,omitempty"`
	GroupId *string `form:"group_id,omitempty" json:"group_id,omitempty"`
	Page    *int    `form:"page,omitempty" json:"page,omitempty"`
	Limit   *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostDevicesIdStreamSessionsJSONBody defines parameters for PostDevicesIdStreamSessions.
type PostDevicesIdStreamSessionsJSONBody struct {
	Fps        *int    `json:"fps,omitempty"`
	Resolution *string `json:"resolution,omitempty"`
}

// PostEnrollmentTokensJSONBody defines parameters for PostEnrollmentTokens.
type PostEnrollmentTokensJSONBody struct {
	BoundGroupId *string `json:"bound_group_id,omitempty"`
}

// PostAgentKeysJSONRequestBody defines body for PostAgentKeys for application/json ContentType.
type PostAgentKeysJSONRequestBody PostAgentKeysJSONBody

// PatchAgentKeysKeyIdJSONRequestBody defines body for PatchAgentKeysKeyId for application/json ContentType.
type PatchAgentKeysKeyIdJSONRequestBody PatchAgentKeysKeyIdJSONBody

// PostAgentsEnrollJSONRequestBody defines body for PostAgentsEnroll for application/json ContentType.
type PostAgentsEnrollJSONRequestBody = AgentEnrollRequest

// PostAgentsEnrollChallengeJSONRequestBody defines body for PostAgentsEnrollChallenge for application/json ContentType.
type PostAgentsEnrollChallengeJSONRequestBody PostAgentsEnrollChallengeJSONBody

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody PostAuthLoginJSONBody

// PostCommandsJSONRequestBody defines body for PostCommands for application/json ContentType.
type PostCommandsJSONRequestBody = DispatchCommandRequest

// PostDevicesIdStreamSessionsJSONRequestBody defines body for PostDevicesIdStreamSessions for application/json ContentType.
type PostDevicesIdStreamSessionsJSONRequestBody PostDevicesIdStreamSessionsJSONBody

// PostEnrollmentTokensJSONRequestBody defines body for PostEnrollmentTokens for application/json ContentType.
type PostEnrollmentTokensJSONRequestBody PostEnrollmentTokensJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List Agent Keys (V2)
	// (GET /agent-keys)
	GetAgentKeys(w http.ResponseWriter, r *http.Request)
	// Create new Agent Enrollment Key (V2)
	// (POST /agent-keys)
	PostAgentKeys(w http.ResponseWriter, r *http.Request)
	// Revoke Agent Key (V2)
	// (DELETE /agent-keys/{key_id})
	DeleteAgentKeysKeyId(w http.ResponseWriter, r *http.Request, keyId string)
	// Get Agent Key details (V2)
	// (GET /agent-keys/{key_id})
	GetAgentKeysKeyId(w http.ResponseWriter, r *http.Request, keyId string)
	// Update Agent Key (V2)
	// (PATCH /agent-keys/{key_id})
	PatchAgentKeysKeyId(w http.ResponseWriter, r *http.Request, keyId string)
	// List devices bound to an Agent Key (V2)
	// (GET /agent-keys/{key_id}/devices)
	GetAgentKeysKeyIdDevices(w http.ResponseWriter, r *http.Request, keyId string)
	// Finalize Agent Enrollment
	// (POST /agents/enroll)
	PostAgentsEnroll(w http.ResponseWriter, r *http.Request)
	// Request Agent Enrollment Challenge
	// (POST /agents/enroll/challenge)
	PostAgentsEnrollChallenge(w http.ResponseWriter, r *http.Request)
	// List Organization Audit Logs
	// (GET /audit-logs)
	GetAuditLogs(w http.ResponseWriter, r *http.Request, params GetAuditLogsParams)
	// User Login
	// (POST /auth/login)
	PostAuthLogin(w http.ResponseWriter, r *http.Request)
	// User Logout & Session Revocation
	// (POST /auth/logout)
	PostAuthLogout(w http.ResponseWriter, r *http.Request)
	// Retrieve current authenticated session
	// (GET /auth/session)
	GetAuthSession(w http.ResponseWriter, r *http.Request)
	// Dispatch Device Command
	// (POST /commands)
	PostCommands(w http.ResponseWriter, r *http.Request)
	// List Tenant Devices
	// (GET /devices)
	GetDevices(w http.ResponseWriter, r *http.Request, params GetDevicesParams)
	// Get Single Device Details
	// (GET /devices/{id})
	GetDevicesId(w http.ResponseWriter, r *http.Request, id string)
	// Acquire Exclusive Control Lease
	// (POST /devices/{id}/control-leases)
	PostDevicesIdControlLeases(w http.ResponseWriter, r *http.Request, id string)
	// Release Control Lease
	// (DELETE /devices/{id}/control-leases/{leaseId})
	DeleteDevicesIdControlLeasesLeaseId(w http.ResponseWriter, r *http.Request, id string, leaseId string)
	// Renew Control Lease TTL
	// (POST /devices/{id}/control-leases/{leaseId}/renew)
	PostDevicesIdControlLeasesLeaseIdRenew(w http.ResponseWriter, r *http.Request, id string, leaseId string)
	// Request WebRTC Stream Session / Signaling
	// (POST /devices/{id}/stream-sessions)
	PostDevicesIdStreamSessions(w http.ResponseWriter, r *http.Request, id string)
	// List Active Enrollment Tokens
	// (GET /enrollment-tokens)
	GetEnrollmentTokens(w http.ResponseWriter, r *http.Request)
	// Generate One-Time Agent Enrollment Token
	// (POST /enrollment-tokens)
	PostEnrollmentTokens(w http.ResponseWriter, r *http.Request)
	// Revoke Enrollment Token
	// (DELETE /enrollment-tokens/{id})
	DeleteEnrollmentTokensId(w http.ResponseWriter, r *http.Request, id string)
	// Get Enrollment Token by ID
	// (GET /enrollment-tokens/{id})
	GetEnrollmentTokensId(w http.ResponseWriter, r *http.Request, id string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List Agent Keys (V2)
// (GET /agent-keys)
func (_ Unimplemented) GetAgentKeys(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create new Agent Enrollment Key (V2)
// (POST /agent-keys)
func (_ Unimplemented) PostAgentKeys(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Revoke Agent Key (V2)
// (DELETE /agent-keys/{key_id})
func (_ Unimplemented) DeleteAgentKeysKeyId(w http.ResponseWriter, r *http.Request, keyId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get Agent Key details (V2)
// (GET /agent-keys/{key_id})
func (_ Unimplemented) GetAgentKeysKeyId(w http.ResponseWriter, r *http.Request, keyId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update Agent Key (V2)
// (PATCH /agent-keys/{key_id})
func (_ Unimplemented) PatchAgentKeysKeyId(w http.ResponseWriter, r *http.Request, keyId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List devices bound to an Agent Key (V2)
// (GET /agent-keys/{key_id}/devices)
func (_ Unimplemented) GetAgentKeysKeyIdDevices(w http.ResponseWriter, r *http.Request, keyId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Finalize Agent Enrollment
// (POST /agents/enroll)
func (_ Unimplemented) PostAgentsEnroll(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Request Agent Enrollment Challenge
// (POST /agents/enroll/challenge)
func (_ Unimplemented) PostAgentsEnrollChallenge(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List Organization Audit Logs
// (GET /audit-logs)
func (_ Unimplemented) GetAuditLogs(w http.ResponseWriter, r *http.Request, params GetAuditLogsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// User Login
// (POST /auth/login)
func (_ Unimplemented) PostAuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// User Logout & Session Revocation
// (POST /auth/logout)
func (_ Unimplemented) PostAuthLogout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Retrieve current authenticated session
// (GET /auth/session)
func (_ Unimplemented) GetAuthSession(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Dispatch Device Command
// (POST /commands)
func (_ Unimplemented) PostCommands(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List Tenant Devices
// (GET /devices)
func (_ Unimplemented) GetDevices(w http.ResponseWriter, r *http.Request, params GetDevicesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get Single Device Details
// (GET /devices/{id})
func (_ Unimplemented) GetDevicesId(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Acquire Exclusive Control Lease
// (POST /devices/{id}/control-leases)
func (_ Unimplemented) PostDevicesIdControlLeases(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Release Control Lease
// (DELETE /devices/{id}/control-leases/{leaseId})
func (_ Unimplemented) DeleteDevicesIdControlLeasesLeaseId(w http.ResponseWriter, r *http.Request, id string, leaseId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Renew Control Lease TTL
// (POST /devices/{id}/control-leases/{leaseId}/renew)
func (_ Unimplemented) PostDevicesIdControlLeasesLeaseIdRenew(w http.ResponseWriter, r *http.Request, id string, leaseId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Request WebRTC Stream Session / Signaling
// (POST /devices/{id}/stream-sessions)
func (_ Unimplemented) PostDevicesIdStreamSessions(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List Active Enrollment Tokens
// (GET /enrollment-tokens)
func (_ Unimplemented) GetEnrollmentTokens(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Generate One-Time Agent Enrollment Token
// (POST /enrollment-tokens)
func (_ Unimplemented) PostEnrollmentTokens(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Revoke Enrollment Token
// (DELETE /enrollment-tokens/{id})
func (_ Unimplemented) DeleteEnrollmentTokensId(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get Enrollment Token by ID
// (GET /enrollment-tokens/{id})
func (_ Unimplemented) GetEnrollmentTokensId(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAgentKeys operation middleware
func (siw *ServerInterfaceWrapper) GetAgentKeys(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAgentKeys(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAgentKeys operation middleware
func (siw *ServerInterfaceWrapper) PostAgentKeys(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAgentKeys(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAgentKeysKeyId operation middleware
func (siw *ServerInterfaceWrapper) DeleteAgentKeysKeyId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "key_id" -------------
	var keyId string

	err = runtime.BindStyledParameterWithOptions("simple", "key_id", chi.URLParam(r, "key_id"), &keyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAgentKeysKeyId(w, r, keyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAgentKeysKeyId operation middleware
func (siw *ServerInterfaceWrapper) GetAgentKeysKeyId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "key_id" -------------
	var keyId string

	err = runtime.BindStyledParameterWithOptions("simple", "key_id", chi.URLParam(r, "key_id"), &keyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAgentKeysKeyId(w, r, keyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchAgentKeysKeyId operation middleware
func (siw *ServerInterfaceWrapper) PatchAgentKeysKeyId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "key_id" -------------
	var keyId string

	err = runtime.BindStyledParameterWithOptions("simple", "key_id", chi.URLParam(r, "key_id"), &keyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchAgentKeysKeyId(w, r, keyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAgentKeysKeyIdDevices operation middleware
func (siw *ServerInterfaceWrapper) GetAgentKeysKeyIdDevices(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "key_id" -------------
	var keyId string

	err = runtime.BindStyledParameterWithOptions("simple", "key_id", chi.URLParam(r, "key_id"), &keyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAgentKeysKeyIdDevices(w, r, keyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAgentsEnroll operation middleware
func (siw *ServerInterfaceWrapper) PostAgentsEnroll(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAgentsEnroll(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAgentsEnrollChallenge operation middleware
func (siw *ServerInterfaceWrapper) PostAgentsEnrollChallenge(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAgentsEnrollChallenge(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuditLogs operation middleware
func (siw *ServerInterfaceWrapper) GetAuditLogs(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAuditLogsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuditLogs(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthLogout operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthSession operation middleware
func (siw *ServerInterfaceWrapper) GetAuthSession(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostCommands operation middleware
func (siw *ServerInterfaceWrapper) PostCommands(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostCommands(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDevices operation middleware
func (siw *ServerInterfaceWrapper) GetDevices(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDevicesParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "group_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "group_id", r.URL.Query(), &params.GroupId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "group_id", Err: err})
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDevices(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDevicesId operation middleware
func (siw *ServerInterfaceWrapper) GetDevicesId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDevicesId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostDevicesIdControlLeases operation middleware
func (siw *ServerInterfaceWrapper) PostDevicesIdControlLeases(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDevicesIdControlLeases(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteDevicesIdControlLeasesLeaseId operation middleware
func (siw *ServerInterfaceWrapper) DeleteDevicesIdControlLeasesLeaseId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "leaseId" -------------
	var leaseId string

	err = runtime.BindStyledParameterWithOptions("simple", "leaseId", chi.URLParam(r, "leaseId"), &leaseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "leaseId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDevicesIdControlLeasesLeaseId(w, r, id, leaseId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostDevicesIdControlLeasesLeaseIdRenew operation middleware
func (siw *ServerInterfaceWrapper) PostDevicesIdControlLeasesLeaseIdRenew(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "leaseId" -------------
	var leaseId string

	err = runtime.BindStyledParameterWithOptions("simple", "leaseId", chi.URLParam(r, "leaseId"), &leaseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "leaseId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDevicesIdControlLeasesLeaseIdRenew(w, r, id, leaseId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostDevicesIdStreamSessions operation middleware
func (siw *ServerInterfaceWrapper) PostDevicesIdStreamSessions(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDevicesIdStreamSessions(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEnrollmentTokens operation middleware
func (siw *ServerInterfaceWrapper) GetEnrollmentTokens(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEnrollmentTokens(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostEnrollmentTokens operation middleware
func (siw *ServerInterfaceWrapper) PostEnrollmentTokens(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostEnrollmentTokens(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteEnrollmentTokensId operation middleware
func (siw *ServerInterfaceWrapper) DeleteEnrollmentTokensId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteEnrollmentTokensId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEnrollmentTokensId operation middleware
func (siw *ServerInterfaceWrapper) GetEnrollmentTokensId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEnrollmentTokensId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/agent-keys", wrapper.GetAgentKeys)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/agent-keys", wrapper.PostAgentKeys)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/agent-keys/{key_id}", wrapper.DeleteAgentKeysKeyId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/agent-keys/{key_id}", wrapper.GetAgentKeysKeyId)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/agent-keys/{key_id}", wrapper.PatchAgentKeysKeyId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/agent-keys/{key_id}/devices", wrapper.GetAgentKeysKeyIdDevices)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/agents/enroll", wrapper.PostAgentsEnroll)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/agents/enroll/challenge", wrapper.PostAgentsEnrollChallenge)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/audit-logs", wrapper.GetAuditLogs)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.PostAuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.PostAuthLogout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/session", wrapper.GetAuthSession)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/commands", wrapper.PostCommands)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/devices", wrapper.GetDevices)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/devices/{id}", wrapper.GetDevicesId)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/devices/{id}/control-leases", wrapper.PostDevicesIdControlLeases)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/devices/{id}/control-leases/{leaseId}", wrapper.DeleteDevicesIdControlLeasesLeaseId)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/devices/{id}/control-leases/{leaseId}/renew", wrapper.PostDevicesIdControlLeasesLeaseIdRenew)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/devices/{id}/stream-sessions", wrapper.PostDevicesIdStreamSessions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/enrollment-tokens", wrapper.GetEnrollmentTokens)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/enrollment-tokens", wrapper.PostEnrollmentTokens)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/enrollment-tokens/{id}", wrapper.DeleteEnrollmentTokensId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/enrollment-tokens/{id}", wrapper.GetEnrollmentTokensId)
	})

	return r
}
