-- Phase 1.2.1 Rollback Core Database Migration

DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS enrollment_tokens CASCADE;
DROP TABLE IF EXISTS proxy_assignments CASCADE;
DROP TABLE IF EXISTS proxies CASCADE;
DROP TABLE IF EXISTS command_outbox CASCADE;
DROP TABLE IF EXISTS command_events CASCADE;
DROP TABLE IF EXISTS commands CASCADE;
DROP TABLE IF EXISTS control_leases CASCADE;
DROP TABLE IF EXISTS device_heartbeats CASCADE;
DROP TABLE IF EXISTS device_agents CASCADE;
DROP TABLE IF EXISTS devices CASCADE;
DROP TABLE IF EXISTS user_roles CASCADE;
DROP TABLE IF EXISTS role_permissions CASCADE;
DROP TABLE IF EXISTS permissions CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS organization_memberships CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS organizations CASCADE;
